server:
  port: 8081
  servlet:
    context-path:
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog?user=postgres&currentSchema=blog
    password: root
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

